#!/usr/bin/env node

const args = require("minimist")(process.argv.slice(2));
const http = require("http");
const url = require("url");
const path = require("path");
const fs = require("fs");
const imageSize = require("image-size");
const Dir = require("./Dir");
const isImage = require("./isImage");
let password;

function pw(str, query)
{
    if (!password) {
        if (query) {
            if (str.indexOf("?") !== -1) {
                str += "&" + query;
            } else {
                str += "?" + query;
            }
        }
        return str;
    }

    if (str.indexOf("?") !== -1) {
        str += "&pw=" + password;
    } else {
        str += "?pw=" + password;
    }
    if (query) {
        str += "&" + query;
    }
    return str;
}

if (!args.dir) {
    console.error("No --dir");
    process.exit(1);
}

if (args.dir[args.dir.length - 1] !== "/") {
    args.dir += "/";
}
if (!args.port) {
    console.error("No --port");
    process.exit(1);
}

password = args.password;

if (args.watch) {
    fs.watch(__dirname, ev => {
        console.log("got change", ev);
        process.exit(0);
    });
}

function linksHTML(response, filePath)
{
    fs.readFile(filePath, "utf-8", (err, data) => {
        if (err) {
            response.writeHead(404, {"Content-Type": "text/plain"});
            response.write(err + "\n");
            response.end();
            return;
        }

        const links = data.split("\n").filter(x => x.startsWith("http")).map(x => {
            return `    <p><a href="${pw(x)}">${x}</a></p>`;
        }).join("\n");

        response.writeHead(200);
        const payload = `<html>
  <head>
  </head>
  <body>
${links}
  </body>`;

        response.write(payload);
        response.end();
    });
}

function imageHTML(response, filepath)
{
    imageSize(filepath, (err, dimensions) => {
        const str = `
<html>
  <head title="${filepath}">
    <style>
* {
    font-size: 25px;
    margin: 0;
    padding: 0;
}
.imgbox {
    display: grid;
    height: 100%;
}
.center-fit {
    max-width: 100%;
    max-height: 100vh;
    margin: auto;
}
    </style>
  </head>
  <body>
     <p>
&nbsp;
     </p>
     <p>
       &nbsp;&nbsp;&nbsp;&nbsp;<a href="${pw(filepath, 'prev')}">Previous</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="${pw(filepath, 'next')}">Next</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="${pw(path.dirname(filepath))}">Dir</a>
     </p>
     <a href="${pw(filepath, 'next')}">
       <div class="imgbox">
         <img class="center-fit" src="${pw(filepath, 'data')}"/>
       </div>
     </a>
  </body>
</html>`;
        response.write(str);
        response.end();
    });
}

function dirHTML(url, response, dir, query)
{
    let str = `
<html>
  <head title="${dir.relative}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
* {
  box-sizing: border-box;
}

img {
  width: 100px;
  heigh: 100px;
}
    </style>
  </head>
  <body>
`;
    if (dir.bookmarks) {
        str += `<p><a href="${pw(path.join(dir.relative, 'bookmark.url'))}">Bookmarks</a></p>\n`;
    }
    // console.log(dir, dir.relative);
    let images;
    if (query.indexOf("z") !== -1) {
        images = [];
        while (dir.images.length) {
            images.push(dir.images.splice(Math.floor(Math.random() * dir.images.length), 1)[0]);
        }
        if (images.length) {
            str += `<p><a href="${pw(dir.relative)}">Unshuffle</a></p>\n`;
        }
    } else {
        images = dir.images;
        if (images.length) {
            str += `<p><a href="${pw(dir.relative, 'z')}">Shuffle</a></p>\n`;
        }
    }
    dir.dirs.forEach(dirpath => {
        str += `<p><a href="${pw(path.join(dir.relative, dirpath))}">${dirpath}</a></p>
`;
    });
    images.forEach(img => {
        str += `<p><a href="${pw(path.join(dir.relative, img))}"><img src="${pw(path.join(dir.relative, img), 'data')}"></img></a></p>\n`;
    });
    str += "</body>\n</html>";

    response.write(str);
    response.end();
}

function stat(fp)
{
    try {
        return fs.statSync(fp);
    } catch (err) {
    }
    return undefined;
}

http.createServer(function(request, response) {
    // console.log(request.url);
    const u = url.parse(request.url);
    u.pathname = decodeURIComponent(u.pathname);
    // console.log(u.pathname);
    // console.log(u);
    const query = String(u.query).split("&");
    // console.log(query, `pw=${password}`, query.indexOf(`pw=${password}`));
    if (password && query.indexOf(`pw=${password}`) === -1) {
        response.writeHead(403);
        response.end();
        return;
    }

    const filePath = path.join(args.dir, u.pathname);
    let statVal = stat(filePath);
    // console.log(filePath, statVal);
    if (!statVal) {
        response.writeHead(301, { Location: pw("/") });
        response.end();
        return;
    }

    // console.log(u.query);

    if (statVal.isDirectory()) {
        const d = new Dir(args.dir, filePath);
        // console.log(d);
        // imagesInDir(filePath);
        dirHTML(u, response, d, query);
        return;
    }

    if (statVal.isFile() && isImage(filePath)) {
        // console.log("got here", u.pathname, u.query);
        const d = new Dir(args.dir, path.dirname(filePath));
        if (query.indexOf("data") !== -1) {
            fs.readFile(filePath, "binary", (err, file) => {
                if (err) {
                    response.writeHead(404, {"Content-Type": "text/plain"});
                    response.write(err + "\n");
                    response.end();
                    return;
                }

                response.writeHead(200);
                response.write(file, "binary");
                response.end();
            });
            return;
        }

        if (query.indexOf("next") !== -1 || query.indexOf("prev") !== -1) {
            let idx = d.images.indexOf(path.basename(u.pathname));
            if (idx === -1) {
                imageHTML(response, u.pathname);
                return;
            }
            if (query.indexOf("next") !== -1) {
                if (++idx === d.images.length) {
                    idx = 0;
                }
            } else {
                if (idx-- === 0) {
                    idx = d.images.length - 1;
                }
            }

            response.writeHead(301, { Location: `${pw(path.join(d.relative, d.images[idx]))}` });
            response.end();
            return;
        }

        imageHTML(response, u.pathname);
        return;
    } else if (filePath.endsWith(".url")) {
        linksHTML(response, filePath);
        return;
    }

    response.writeHead(404);
    response.end();
    return;

    // console.log(statVal);

    // const filename = path.join(process.cwd(), uri);

    // fs.exists(filename, function(exists) {
    //     if(!exists) {
    //         response.writeHead(404, {"Content-Type": "text/plain"});
    //         response.write("404 Not Found\n");
    //         response.end();
    //         return;
    //     }

    //     if (fs.statSync(filename).isDirectory()) filename += '/index.html';

    //     fs.readFile(filename, "binary", function(err, file) {
    //         if(err) {
    //             response.writeHead(500, {"Content-Type": "text/plain"});
    //             response.write(err + "\n");
    //             response.end();
    //             return;
    //         }

    //         response.writeHead(200);
    //         response.write(file, "binary");
    //         response.end();
    //     });
    // });
}).listen(parseInt(args.port, 10));

console.log(args);
